### ISSUE TITLE
update image with vignette builder dependencies

### ISSUE THREAD

**Issue by egouldo** [metamelb-repliCATS/aggreCAT#12]
```yaml
      - name: vignette-builder
        run:  install.packages("R.rsp"); remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
```
Ill bake this into the image at a later date.

_Originally posted by @psychtek in https://github.com/metamelb-repliCATS/aggreCAT/pull/11#pullrequestreview-1096979070_
