### ISSUE TITLE
GH Action to render README.qmd ?

### ISSUE THREAD

**Issue by egouldo** [metamelb-repliCATS/aggreCAT#17]
No version of `devtools::build_readme()` for `.qmd` files https://devtools.r-lib.org/reference/build_rmd.html ... so, should we set up a GH action to instead render the README automatically? I've been forgetting to render this manually after I make changes to the README.

See https://github.com/quarto-dev/quarto-actions/tree/main/render for a GH actions for `quarto_render()`, usage here (🗒️ I've substituted `to: html` with `to: md`, which is what we want, untested, however):

```yaml

- name: Render Quarto Project
  uses: quarto-dev/quarto-actions/render@v2
  with:
    to: md # If set, it will be equivalent to `quarto render --to md`
    path: source-folder # By default, the current working dir is used i.e `quarto render .`
```
